language: node_js
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
node_js:
- '0.12'
before_script:
- npm install -g gulp
- bower install
script: gulp deploy
notifications:
  email:
    on_success: change
    on_failure: always
branches:
  only:
    - master
